# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# Run locally with: goreleaser --rm-dist --snapshot --skip-publish
project_name: lotto

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
- binary: '{{ .ProjectName }}'
  main: ./main.go
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X main.Version={{.Version}} -X main.GitCommit={{.Commit}}
    - -a -extldflags "-static"
  goos:
      - windows
      - linux
      - darwin
  goarch:
      - amd64

archives:
- format: zip
- replacements:
    darwin: macOS
  files:
      - LICENSE

nfpms:
  -
    package_name: g2d
    vendor: Luca Sepe
    homepage: https://lucasepe.it/
    maintainer: Luca Sepe <luca.sepe@gmail.com>
    description: Lotto. 
    license: MIT
    replacements:
      amd64: 64-bit
    formats:
      - deb
      - rpm
